version: '3.8'

services:

  minio:
      image: minio/minio:latest
      command: server /data --console-address ":9001"
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio12345
      ports:
        - "9000:9000"  # S3 API
        - "9001:9001"  # Web Console
      volumes:
        - ./minio-data:/data
        
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

networks:
  link-enlist-network:
